- hosts: "{{inventory_hostname}}"
  roles:
    - { role: datadog.datadog, become: yes }
  vars:
    datadog_api_key: "{{your_api_key}}"
    datadog_site: "datadoghq.com"
    datadog_config:
      tags:
        - "env:{{env}}"
        - "service:management"
        - "application:{{application}}"
        - "managedby:{{company}}"
        - "role:{{role}}"
        - "datacenter:{{datacenter}}"
        - "kernel:linux"
        - "excludemon:no"
      log_level: INFO
      process_agent_enabled: true
    datadog_checks:
      process:
        init_config:
        instances:
          - name: ssh
            search_string: ['ssh', 'sshd']
          - name: syslog
            search_string: ['rsyslog']
            cpu_check_interval: 0.2
            exact_match: true
            ignore_denied_access: true
    network_config:
      enabled: true
